#
# Build stage
#
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /ChatRoom
COPY . /ChatRoom/
RUN mvn clean package

#
# Package stage
#
FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /ChatRoom/target/*.jar /ChatRoom/ChatRoom.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]